import type {
  BugDNA,
  AITriage,
  RelatedIssue,
  CausalGraph,
  ReproductionCapsule,
  ResolutionConfidence,
} from '../../types/intelligence';

import { apiClient } from './client';

/**
 * Fetch Bug DNA generated by the intelligence service.
 */
export const getBugDna = (
  issueId: string
): Promise<BugDNA | null> => {
  return apiClient.get<BugDNA | null>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/bug-dna`
  );
};

/**
 * Fetch AI triage generated by the intelligence service.
 */
export const getAiTriage = (
  issueId: string
): Promise<AITriage | null> => {
  return apiClient.get<AITriage | null>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/triage`
  );
};

/**
 * Accept AI triage recommendations.
 *
 * The backend is responsible for recording the decision,
 * authorization and audit event.
 */
export const acceptAiTriage = (
  issueId: string
): Promise<void> => {
  return apiClient.post<void>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/triage/accept`
  );
};

/**
 * Reject/override AI triage recommendations.
 *
 * The backend is responsible for recording the decision,
 * authorization and audit event.
 */
export const rejectAiTriage = (
  issueId: string
): Promise<void> => {
  return apiClient.post<void>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/triage/reject`
  );
};

/**
 * Fetch related issues identified by the intelligence service.
 */
export const getRelatedIssues = (
  issueId: string
): Promise<RelatedIssue[]> => {
  return apiClient.get<RelatedIssue[]>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/related`
  );
};

/**
 * Fetch the causal relationship graph for an issue.
 */
export const getCausalGraph = (
  issueId: string
): Promise<CausalGraph | null> => {
  return apiClient.get<CausalGraph | null>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/causal-graph`
  );
};

/**
 * Fetch the reproduction capsule generated for an issue.
 */
export const getReproductionCapsule = (
  issueId: string
): Promise<ReproductionCapsule | null> => {
  return apiClient.get<ReproductionCapsule | null>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/reproduction`
  );
};

/**
 * Fetch resolution confidence and its evidence items.
 */
export const getResolutionConfidence = (
  issueId: string
): Promise<ResolutionConfidence | null> => {
  return apiClient.get<ResolutionConfidence | null>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/resolution-confidence`
  );
};

/**
 * Request an evidence-item verification update.
 *
 * The backend/intelligence service owns:
 * - evidence validation
 * - confidence calculation
 * - authorization
 * - audit logging
 * - release-risk recalculation
 */
export const verifyConfidenceItem = (
  issueId: string,
  itemId: string,
  verified: boolean
): Promise<ResolutionConfidence> => {
  return apiClient.patch<ResolutionConfidence>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/resolution-confidence/evidence/${encodeURIComponent(itemId)}`,
    { verified }
  );
};
