import type {
  BugDNA,
  AITriage,
  RelatedIssue,
  CausalGraph,
  ReproductionCapsule,
  ResolutionConfidence,
} from '../../types/intelligence';

import { apiClient } from './client';

export interface IntelligenceResponse {
  bugDna: BugDNA;
  triage: AITriage;
  reproductionCapsule: ReproductionCapsule;
  resolutionConfidence: ResolutionConfidence;
  risk: any;
}

/**
 * Fetch Bug DNA generated by the intelligence service.
 */
export const getBugDna = async (
  issueId: string
): Promise<BugDNA | null> => {
  try {
    const res = await apiClient.get<IntelligenceResponse>(
      `/issues/${encodeURIComponent(issueId)}/intelligence`
    );
    return res?.bugDna ?? null;
  } catch {
    return null;
  }
};

/**
 * Fetch AI triage generated by the intelligence service.
 */
export const getAiTriage = async (
  issueId: string
): Promise<AITriage | null> => {
  try {
    const res = await apiClient.get<IntelligenceResponse>(
      `/issues/${encodeURIComponent(issueId)}/intelligence`
    );
    return res?.triage ?? null;
  } catch {
    return null;
  }
};

/**
 * Accept AI triage recommendations.
 */
export const acceptAiTriage = (
  issueId: string
): Promise<void> => {
  return apiClient.post<void>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/triage/accept`
  );
};

/**
 * Reject/override AI triage recommendations.
 */
export const rejectAiTriage = (
  issueId: string
): Promise<void> => {
  return apiClient.post<void>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/triage/reject`
  );
};

/**
 * Fetch related issues identified by the intelligence service.
 */
export const getRelatedIssues = async (
  issueId: string
): Promise<RelatedIssue[]> => {
  try {
    const data = await apiClient.get<RelatedIssue[]>(
      `/issues/${encodeURIComponent(issueId)}/related`
    );
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
};

/**
 * Fetch the causal relationship graph for an issue.
 *
 * The backend does not currently expose this endpoint.
 * Returns null (unavailable) rather than propagating the 404,
 * so that the causal graph being absent does not fail the entire
 * Issue Workspace Promise.all().
 */
export const getCausalGraph = async (
  issueId: string
): Promise<CausalGraph | null> => {
  try {
    return await apiClient.get<CausalGraph | null>(
      `/issues/${encodeURIComponent(issueId)}/intelligence/causal-graph`
    );
  } catch {
    // Endpoint not implemented — treat as unavailable.
    return null;
  }
};

/**
 * Fetch the reproduction capsule generated for an issue.
 */
export const getReproductionCapsule = async (
  issueId: string
): Promise<ReproductionCapsule | null> => {
  try {
    return await apiClient.get<ReproductionCapsule>(
      `/issues/${encodeURIComponent(issueId)}/reproduction-capsule`
    );
  } catch {
    return null;
  }
};

/**
 * Fetch resolution confidence and its evidence items.
 */
export const getResolutionConfidence = async (
  issueId: string
): Promise<ResolutionConfidence | null> => {
  try {
    return await apiClient.get<ResolutionConfidence>(
      `/issues/${encodeURIComponent(issueId)}/resolution-confidence`
    );
  } catch {
    return null;
  }
};

/**
 * Request an evidence-item verification update.
 */
export const verifyConfidenceItem = (
  issueId: string,
  itemId: string,
  verified: boolean
): Promise<ResolutionConfidence> => {
  return apiClient.patch<ResolutionConfidence>(
    `/issues/${encodeURIComponent(issueId)}/intelligence/resolution-confidence/evidence/${encodeURIComponent(itemId)}`,
    { verified }
  );
};
